### ISSUE TITLE
[Question] How to benchmark the execution? 

### ISSUE THREAD

**Issue by Yevgnen** [epwalsh/batched-fn#17]
Thanks for the great package! 

When tuning `max_batch_size` and `max_delay`, I wonder how can I benchmark or record the GPU execution time for a batch? I don't know where to put the time related codes in the code due to my limited knowledge to Rust. It might be easy for a single request but I have no idea for a batch.

Thanks.

**Comment by epwalsh** [comment]
Hi, you might want to start by putting timing code in the `handler` closure, e.g. right here: https://github.com/epwalsh/batched-fn/blob/93b3ffcf0becd30838389e70b329c3262b792b46/examples/example.rs#L36-L38

That will tell you how it takes to process each batch at a given batch size.

In general (for deep learning models, at least) I would set `max_batch_size` as large as you can without running out of memory, and `max_delay` small relative to the time it takes to process a batch.

**Comment by Yevgnen** [comment]
Hi, thanks for the suggestion. I have one more question, how about `channel_cap`?

**Comment by epwalsh** [comment]
When you set `channel_cap`, `batched_fn!` will internally use a [bounded flume channel](https://docs.rs/flume/latest/flume/fn.bounded.html) instead of an unbounded one. As a result, calls to your batched fn might return [`Error::Full`](https://docs.rs/batched-fn/0.2.3/batched_fn/enum.Error.html#variant.Full).

One reason you might want to use this feature is to return 503 errors when your server is getting too many requests at once. In particular, set `channel_cap` to some number greater than `max_batch_size` and then catch `Error::Full` in your server code, and return a 503 error when that happens.

**Comment by Yevgnen** [comment]
Thanks for the explanation!

**Comment by epwalsh** [comment]
You're welcome!
